export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER';
export const SET_PROFILE_USER = 'SET_PROFILE_USER';
export const REMOVE_LOGGED_IN_USER = 'REMOVE_LOGGED_IN_USER';
export const SET_FORGOT_USER = 'SET_FORGOT_USER';
export const SET_SEARCH_FILTERS = 'SET_SEARCH_FILTERS';
export const RESET_SEARCH_FILTERS = 'RESET_SEARCH_FILTERS';
export const MODIFY_SEGMENT_IN_SEARCH = 'MODIFY_SEGMENT_IN_SEARCH';
export const MODIFY_BRAND_IN_SEARCH = 'MODIFY_BRAND_IN_SEARCH';
export const MODIFY_VARIANT_IN_SEARCH = 'MODIFY_VARIANT_IN_SEARCH';
export const MODIFY_CATEGORY_IN_SEARCH = 'MODIFY_CATEGORY_IN_SEARCH';
export const MODIFY_QUERY_IN_SEARCH = 'MODIFY_QUERY_IN_SEARCH';
export const MODIFY_MANUFACTURE_IN_SEARCH = 'MODIFY_MANUFACTURE_IN_SEARCH';


export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
export const UPDATE_QTY_TO_CART = "UPDATE_QTY_TO_CART";
export const REMOVE_ALL_CART = "REMOVE_ALL_CART";
export const ADD_QTY_TO_CART = "ADD_QTY_TO_CART";
export const SUB_QTY_TO_CART = "SUB_QTY_TO_CART";
export const FORGOT_USER = "FORGOT_USER";

export const ADD_ITEM_TO_WISHLIST = "ADD_ITEM_TO_WISHLIST";
export const REMOVE_ITEM_FROM_WISHLIST = "REMOVE_ITEM_FROM_WISHLIST";
export const EMPTY_WISHLIST = "EMPTY_WISHLIST"
export const SET_COMMON_DATA = "SET_COMMON_DATA";
export const SET_COMMON_SETTINGS_DATA = "SET_COMMON_SETTINGS_DATA";